### ISSUE TITLE
3x3 recipes are accessible without a Crafting Table etc

### ISSUE THREAD

**Issue by katubug** [PfisterFactor/QuickerCrafting#21]
This occurs with mod version 0.9.2, Forge 2847. I tested in an isolated instance with only a few mods (JEI, CraftTweaker, The One Probe etc).

What you'd expect it to do:
- Allow only 2x2 crafting unless the player is carrying or has access to some device that gives a 3x3 crafting grid.

What it actually did (bugs only):
- It allows me to craft 3x3 recipes (Boats, Doors, Furnaces etc) even after just spawning into a test world

Steps to reproduce (bugs only):
- Create new Creative World
- Put ingredients in inventory
- Set gamemode to survival
- Attempt to craft a 3x3 recipe

Crash log (use pastebin):
n/a

**Comment by PfisterFactor** [comment]
There is a config option to enable it but it is off by default. Is the config option enabled?

**Comment by katubug** [comment]
Thanks for the quick response! It does seem to be enabled, but I didn't change it - I just installed the mod, started the game, did the above tests, and then filed this report.

    # The distance (in blocks) one needs to be to a crafting table to unlock 3x3 recipes.
    # Set to a negative value to always allow 3x3 recipes.
    # A zero value will never allow 3x3 recipes.
    # A crafting table is looked for in this radius on gui open.
    # Increasing this will have a (small) negative effect on performance.
    # Min: -1
    # Max: 10
    I:CraftingTableRadius=-1

**Comment by PfisterFactor** [comment]
Ah yeah, by default it is set to -1 and 3x3 recipes are always enabled. Set the crafting table radius to the distance away (in blocks) from the crafting table block you desire 3x3 recipes to be unlocked. Additionally, set any valid crafting table items within the config.

You can also change it in game if you click on "Mod Options" and then search for quickercrafting and then click "Config".

If it doesn't work then please tell me, otherwise I'm going to close this issue :).

**Comment by katubug** [comment]
Ah, I see. Sorry, I misunderstood, I thought you meant that by default 3x3 crafting was not available automatically. Sorry for the false alarm! I'll close this. :)
